/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * HomeScene.ls
 */
export class HomeViewBase extends Laya.Scene {
    public GameBox!: Laya.Box;
    public PokerBox!: Laya.Box;
    public timeLabel!: Laya.Label;
    public goldLab!: Laya.Label;
    public ResultBox!: Laya.Box;
    public RetryButton!: Laya.Button;
    public HomeBox!: Laya.Box;
    public StartButton!: Laya.Button;
}

